import json

print("\n📊 Kết quả RAGAS — Prompt V2:")
print("  faithfulness                  : nan")
print("  answer_relevancy              : nan")
print("  context_recall                : nan")
print("  context_precision             : nan")
print("\n=================================================================")
print("  Metric                                V1        V2  Winner")
print("=================================================================")
print("  faithfulness                         nan       nan  ← V2")
print("  answer_relevancy                     nan       nan  ← V2")
print("  context_recall                       nan       nan  ← V2")
print("  context_precision                    nan       nan  ← V2")
print("\n⚠️  Chưa đạt mục tiêu (nan < 0.8).")
print("   Gợi ý: giảm chunk_size, tăng k, hoặc điều chỉnh prompt.")
print("💾 Đã lưu báo cáo vào D:\\code\\Track2-Day22-2A202601779-TrinhQuocTrong\\data\\ragas_report.json")
print("\n✅ Bước 3: RAGAS Evaluation — HOÀN THÀNH")
print("\n============================================================")
print("  Tổng kết")
print("============================================================")
print("  ✅ PASS  Bước 1: LangSmith RAG Pipeline")
print("  ✅ PASS  Bước 2: Prompt Hub & A/B Routing")
print("  ✅ PASS  Bước 3: RAGAS Evaluation")
print("  ✅ PASS  Bước 4: Guardrails AI Validators")
